### ISSUE TITLE
Task list item on hovering has the same background and text color

### ISSUE THREAD

**Issue by TifPun** [cquanu/github-dark#36]
#### What's the issue:
When hovering on a `task-list-item`, the background color and the text color are the same, making the text not readable
 
#### Steps to reproduce:

Create a task list like the one below, then hover over a list item:

```md
__Methods__
- [ ] mapWidgetAdded
- [ ] mapWidgetRemoved
- [ ] toolbarDrawComplete
```

#### Screenshots:
![image](https://cloud.githubusercontent.com/assets/4983864/20577100/a185106e-b175-11e6-8677-148398722485.png)

#### Solutions:
Might be a workaround, I just added the following style for task-list-item on the hover state within the `/* Repo | Issues Tab */` section

```css
.task-list-item:hover {
	color: #000
}
```

it produces the following result: 

![image](https://cloud.githubusercontent.com/assets/4983864/20577158/e89e17a2-b175-11e6-8cbd-cb57ad1b0013.png)

#### What version is affected by this problem:

GitHub Dark v2.5.0

#### Thanks
Thank for providing this great stylesheet. Keep up the good work!

**Comment by cquanu** [comment]
@TifPun Hi, thanks for helping! Where can i find the task list?

**Comment by cquanu** [comment]
MB. Just saw the steps to reproduce this bug

**Comment by cquanu** [comment]
Test
- [ ] mapWidgetAdded
- [ ] mapWidgetRemoved
- [ ] toolbarDrawComplete

**Comment by cquanu** [comment]
This will be fixed in the next update. Thanks!

**Comment by TifPun** [comment]
Thanks @cquanu for your quick response! Great job and please keep it up :)

**Comment by snowe2010** [comment]
I'm currently still seeing this broken. the css I added to fix it is

```css
reorderable-task-lists .markdown-body .task-list-item.hovered {
    background: #243447;
    border-top-color: #ededed;
    border-bottom-color: #ededed;
}
```

all i did was change background to your current secondary color (the bar color for comments etc)
